
# SEO settings
title: valeriu.caraulean
description: "Valeriu Caraulean: personal site & blog"
keywords: "valeriu carualean, .net, geneva, .net developer, .net user group, genevadnug, blog, web"
url: http://caraulean.com
#baseurl: null

#google_analytics: UA-52446115-1
repo: http://github.com/vcaraulean/vcaraulean.github.io
#disqus_shortname: "fernandomoreira"

# Build settings
permalink   : /:year/:title/
#markdown    : kramdown
#highlighter : rouge

paginate: 10
paginate_path: "/page/:num/"
comments: true

#destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  #style: compressed # expanded

# Author settings
author:
  name     : Valeriu Caraulean
  job      : Software engeneer
  bio      : "Enthusiast developer and architect with main focus on everything around .NET and some Microsoft technologies"
  thumb    : /images/me.png
  email    : valeriu@caraulean.com
  url      : http://caraulean.com
  github   : http://github.com/vcaraulean
  twitter  : http://twitter.com/vcaraulean
  linkedin : http://ch.linkedin.com/in/vcaraulean

# social settings
#og_locale: "pt_BR"
twitter_card: "summary_large_image"
twitter_site: "@vcaraulean"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
